### ISSUE TITLE
Fails to build with Boost 1.71.0

### ISSUE THREAD

**Issue by TinfoilSubmarine** [ros-melodic-arch/ros-melodic-rviz#8]
Output of `make -si`:

```
/usr/bin/ld: warning: libboost_thread.so.1.69.0, needed by /usr/lib/gcc/x86_64-pc-linux-gnu/9.2.0/../../../../lib/libOgreMain.so, not found (try using -rpath or -rpath-link)
/usr/bin/ld: /usr/lib/gcc/x86_64-pc-linux-gnu/9.2.0/../../../../lib/libOgreMain.so: undefined reference to `boost::detail::set_tss_data(void const*, boost::shared_ptr<boost::detail::tss_cleanup_function>, void*, bool)'
collect2: error: ld returned 1 exit status
make[2]: *** [src/rviz/CMakeFiles/executable.dir/build.make:181: devel/lib/rviz/rviz] Error 1
make[1]: *** [CMakeFiles/Makefile2:2249: src/rviz/CMakeFiles/executable.dir/all] Error 2
make: *** [Makefile:130: all] Error 2
==> ERROR: A failure occurred in build().
    Aborting...

**Comment by jwhendy** [comment]
Please kindly search past issues prior to opening a new one. See #7.
